#!/usr/bin/env bash
# Test runner for MCP tools - generated by mcp-bash scaffold test
# Usage: ./test/run.sh [--verbose] [--force]
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export MCPBASH_PROJECT_ROOT="${PROJECT_ROOT}"

case "$(uname -s 2>/dev/null)" in
MINGW* | MSYS*)
	# Keep path conversion enabled so Windows-native jq/gojq can open temp files.
	unset MSYS2_ARG_CONV_EXCL
	;;
esac

# Locate mcp-bash binary
MCPBASH_BIN="${MCPBASH_BIN:-}"
if [[ -z "${MCPBASH_BIN}" ]] && command -v mcp-bash >/dev/null 2>&1; then
	MCPBASH_BIN="$(command -v mcp-bash)"
fi
if [[ -z "${MCPBASH_BIN}" ]] && [[ -n "${MCPBASH_HOME:-}" ]] && [[ -x "${MCPBASH_HOME}/bin/mcp-bash" ]]; then
	MCPBASH_BIN="${MCPBASH_HOME}/bin/mcp-bash"
fi
if [[ -z "${MCPBASH_BIN}" ]] && [[ -x "${PROJECT_ROOT}/../bin/mcp-bash" ]]; then
	MCPBASH_BIN="${PROJECT_ROOT}/../bin/mcp-bash"
fi
if [[ -z "${MCPBASH_BIN}" ]] && [[ -x "${PROJECT_ROOT}/bin/mcp-bash" ]]; then
	MCPBASH_BIN="${PROJECT_ROOT}/bin/mcp-bash"
fi
if [[ -z "${MCPBASH_BIN}" ]]; then
	printf 'mcp-bash not found; add to PATH or set MCPBASH_HOME.\n' >&2
	exit 1
fi

VERBOSE="${VERBOSE:-0}"
FORCE="${FORCE:-0}"

while [[ $# -gt 0 ]]; do
	case "$1" in
	--verbose | -v)
		VERBOSE=1
		shift
		;;
	--force | -f)
		FORCE=1
		shift
		;;
	*)
		break
		;;
	esac
done

passed=0
failed=0
skipped=0

# Colors (disabled if not a terminal)
RED=""
GREEN=""
YELLOW=""
RESET=""
if [[ -t 1 ]]; then
	RED="\033[0;31m"
	GREEN="\033[0;32m"
	YELLOW="\033[0;33m"
	RESET="\033[0m"
fi

run_test() {
	local name="$1"
	local args="${2:-{}}"
	local description="${3:-}"

	if [[ -n "${description}" ]]; then
		printf "  %s (%s)... " "${name}" "${description}"
	else
		printf "  %s... " "${name}"
	fi

	local output
	if [[ "${VERBOSE}" == "1" ]]; then
		if "${MCPBASH_BIN}" run-tool "${name}" --args "${args}" --verbose; then
			printf '%sPASS%s\n' "${GREEN}" "${RESET}"
			((passed++))
		else
			printf '%sFAIL%s\n' "${RED}" "${RESET}"
			((failed++))
		fi
	else
		if output=$("${MCPBASH_BIN}" run-tool "${name}" --args "${args}" 2>&1); then
			printf '%sPASS%s\n' "${GREEN}" "${RESET}"
			((passed++))
		else
			printf '%sFAIL%s\n' "${RED}" "${RESET}"
			if [[ -n "${output}" ]]; then
				printf "    Output: %s\n" "${output}" >&2
			fi
			((failed++))
		fi
	fi
}

run_dry_run() {
	local name="$1"
	local args="${2:-{}}"

	printf "  %s (dry-run)... " "${name}"

	local output
	local -a extra_flags=()
	if [[ "${VERBOSE}" == "1" ]]; then
		extra_flags+=(--verbose)
	fi

	if output=$("${MCPBASH_BIN}" run-tool "${name}" --args "${args}" --dry-run "${extra_flags[@]}" 2>&1); then
		printf '%sPASS%s\n' "${GREEN}" "${RESET}"
		((passed++))
	else
		printf '%sFAIL%s\n' "${RED}" "${RESET}"
		if [[ -n "${output}" ]]; then
			printf "    Output: %s\n" "${output}" >&2
		fi
		((failed++))
	fi
}

skip_test() {
	local name="$1"
	local reason="${2:-}"

	printf "  %s... ${YELLOW}SKIP${RESET}" "${name}"
	if [[ -n "${reason}" ]]; then
		printf " (%s)" "${reason}"
	fi
	printf "\n"
	((skipped++))
}

# Discover and validate tools exist
printf "Discovering tools...\n"
if ! "${MCPBASH_BIN}" validate --project-root "${PROJECT_ROOT}" >/dev/null 2>&1; then
	printf '%sError: Project validation failed. Run '\''mcp-bash validate'\'' for details.%s\n' "${RED}" "${RESET}" >&2
	if [[ "${FORCE}" != "1" ]]; then
		printf "Use --force to run tests anyway.\n" >&2
		exit 1
	fi
	printf '%sContinuing anyway (--force)...%s\n' "${YELLOW}" "${RESET}" >&2
fi

printf "\nRunning tests...\n"

# ============================================================================
# ADD YOUR TESTS BELOW
# ============================================================================
#
# Examples:
#
#   # Basic tool invocation
#   run_test "hello" '{"name":"World"}'
#   # Run all per-tool smoke scripts (if present)
#   # for f in "${PROJECT_ROOT}"/tools/*/smoke.sh; do [ -x "$f" ] && "$f" || exit 1; done
#
#   # Test with description
#   run_test "hello" '{}' "default greeting"
#
#   # Dry-run validation (checks args/metadata without executing)
#   run_dry_run "hello" '{"name":"Test"}'
#
#   # Pass roots (comma-separated) and timeout overrides
#   # run_test "hello" '{"name":"Roots"}' "" "--roots" "/repo,/other" "--timeout" "15"
#   # Extract structuredContent from run-tool output
#   # output="$(mcp-bash run-tool hello --args '{"name":"World"}')"
#   # message="$(printf '%s\n' "${output}" | jq -r '.structuredContent.message // .content[0].text')"
#   # test_assert_eq "Hello World" "${message}"
#
#   # Expected failure pattern
#   # if mcp-bash run-tool hello --args '"not-an-object"' >/dev/null 2>&1; then
#   #     test_fail "hello should reject non-object args"
#   # fi
#
#   # Skip a test conditionally
#   if [[ -z "${API_KEY:-}" ]]; then
#       skip_test "api-tool" "API_KEY not set"
#   else
#       run_test "api-tool" '{"query":"test"}'
#   fi
#
#   # Git fixtures: disable signing to avoid global gpg/1Password hooks breaking tests
#   # git config commit.gpgsign false
#   # git config tag.gpgsign false
#
# ============================================================================

# TODO: Add your tool tests here
# run_test "your-tool" '{"arg":"value"}'

# ============================================================================
# END OF TESTS
# ============================================================================

printf "\n"
printf "Results: ${GREEN}%d passed${RESET}, ${RED}%d failed${RESET}" "${passed}" "${failed}"
if [[ "${skipped}" -gt 0 ]]; then
	printf ", ${YELLOW}%d skipped${RESET}" "${skipped}"
fi
printf "\n"

[[ "${failed}" -eq 0 ]] || exit 1
