#!/usr/bin/env bats
# Unit tests for doctor --dry-run/--fix contracts and shim repair.

load '../../node_modules/bats-support/load'
load '../../node_modules/bats-assert/load'
load '../common/fixtures'
load '../common/ndjson'

setup() {
	[ -n "${TEST_JSON_TOOL_BIN:-}" ] || skip "jq/gojq required"
}

@test "doctor_modes: doctor rejects --fix + --dry-run" {
	run "${MCPBASH_HOME}/bin/mcp-bash" doctor --fix --dry-run
	assert_equal "2" "${status}"
}

@test "doctor_modes: doctor --dry-run --json proposes shim action on managed install" {
	HOME_ROOT="${BATS_TEST_TMPDIR}/home"
	export HOME="${HOME_ROOT}"
	export XDG_DATA_HOME="${HOME}/.local/share"
	export XDG_BIN_HOME="${HOME}/.local/bin"
	mkdir -p "${HOME}/.local/share" "${HOME}/.local/bin"
	MANAGED_ROOT="${HOME}/.local/share/mcp-bash"
	mkdir -p "${MANAGED_ROOT}"
	(
		cd "${MCPBASH_HOME}" || exit 1
		tar -cf - --exclude .git bin lib VERSION | (cd "${MANAGED_ROOT}" && tar -xf -)
	)
	printf '%s\n' '{"managed":true}' >"${MANAGED_ROOT}/INSTALLER.json"

	[ ! -e "${HOME}/.local/bin/mcp-bash" ]

	run "${MANAGED_ROOT}/bin/mcp-bash" doctor --dry-run --json
	assert_success
	printf '%s\n' "${output}" >"${BATS_TEST_TMPDIR}/doctor_dry.json"
	jq -e '.exitCode == 0' "${BATS_TEST_TMPDIR}/doctor_dry.json" >/dev/null
	jq -e '.proposedActions | type == "array"' "${BATS_TEST_TMPDIR}/doctor_dry.json" >/dev/null
	jq -e '.proposedActions[0].id == "shim.ensure"' "${BATS_TEST_TMPDIR}/doctor_dry.json" >/dev/null
}

@test "doctor_modes: doctor --fix --json creates shim on managed install" {
	HOME_ROOT="${BATS_TEST_TMPDIR}/home"
	export HOME="${HOME_ROOT}"
	export XDG_DATA_HOME="${HOME}/.local/share"
	export XDG_BIN_HOME="${HOME}/.local/bin"
	mkdir -p "${HOME}/.local/share" "${HOME}/.local/bin"
	MANAGED_ROOT="${HOME}/.local/share/mcp-bash"
	mkdir -p "${MANAGED_ROOT}"
	(
		cd "${MCPBASH_HOME}" || exit 1
		tar -cf - --exclude .git bin lib VERSION | (cd "${MANAGED_ROOT}" && tar -xf -)
	)
	printf '%s\n' '{"managed":true}' >"${MANAGED_ROOT}/INSTALLER.json"

	run "${MANAGED_ROOT}/bin/mcp-bash" doctor --fix --json
	assert_success
	printf '%s\n' "${output}" >"${BATS_TEST_TMPDIR}/doctor_fix.json"
	jq -e '.exitCode == 0' "${BATS_TEST_TMPDIR}/doctor_fix.json" >/dev/null

	shim_path="${HOME}/.local/bin/mcp-bash"
	[ -e "${shim_path}" ]

	case "$(uname -s 2>/dev/null || printf '')" in
	MINGW* | MSYS* | CYGWIN*)
		assert_contains "mcp-bash managed shim; generated by doctor --fix" "$(cat "${shim_path}")"
		;;
	*)
		[ -L "${shim_path}" ]
		;;
	esac
}
